#!/sbin/runscript
# Distributed under the terms of the GNU General Public License v2

command="/usr/bin/serf"
command_args="agent ${options}"
command_background="true"
extra_started_commands="reload"
pidfile="/run/serf/${RC_SVCNAME}.pid"

depend() {
	need net
}

start_pre() {
	checkpath --directory /run/serf
}

reload() {
	ebegin "Reloading ${RC_SVCNAME}"

	start-stop-daemon --signal HUP --pidfile $pidfile

	eend $? "Failed to reload ${RC_SVCNAME}"
}
